from django.urls import path
from .views import UpdatePaymentStatusAPIView,CreateOrderAPIView,ProductListAPIView,GetUserAPIView,CreateProductAPIView,TotalPriceShopOrdersAPIView,ProductOrderListAPIView,TotalOrdersAPIView,LoginAdminAPIView,GetPositionQueueAPIView,CreateDiscountCodeAPIView,UpdatePositionAPIView,UpdateUserCreditAPIView,UserApiView,AssignWorkerToPositionAPIView,AllOrdersAPIView,WorkerShiftUpdateAPIView,WorkerCreateAPIView,WorkerDeleteAPIView,ValidateDiscountCodeAPIView,CarDetailView,UserShopOrdersAPIView,UserOrdersAPIView,UpdateOrderDetailsAPIView,SignupAPIView,UserProfileUpdateAPIView,UserCarsAPIView, LoginAPIView,CarAPIView,CarDetailAPIView,WorkersAPIView,PositionAPIView, AssignCarToPositionAPIView,PositionSetupAPIView,ServiceViewSet,OrderViewSet
from django.urls import path, include

urlpatterns = [
    path('user/<int:user_id>/',GetUserAPIView.as_view(),name='user'),
    path('signup/', SignupAPIView.as_view(), name='signup'),
    path('login/', LoginAPIView.as_view(), name='login'),
    path('adminlogin/', LoginAdminAPIView.as_view(), name='adminLogin'),
    path('cars/', CarAPIView.as_view(), name='car-list'),
    path('user/<int:user_id>/cars/', UserCarsAPIView.as_view(), name='user-cars'),
    path('user/<int:user_id>/update/', UserProfileUpdateAPIView.as_view(), name='user-update'),
    path('usercredit/',UpdateUserCreditAPIView.as_view(), name='update-user-creadit'),
    path('userView/',UserApiView.as_view(),name="userView"),
    path('carsup/<int:car_id>/', CarDetailAPIView.as_view(), name='car-detail'),
    path('workers/', WorkersAPIView.as_view(), name='workers-list-create'),
    path('addworker/', WorkerCreateAPIView.as_view(), name='add-workers'),
    path('deleteworker/',WorkerDeleteAPIView.as_view(), name='delete-workers'),
    path('updateworker/<int:worker_id>/', WorkerShiftUpdateAPIView.as_view(), name='update-worker-shift'),
    path('workerassign/',AssignWorkerToPositionAPIView.as_view(), name='assign-workers'),
    path('setuppositions/', PositionSetupAPIView.as_view(), name='setup-positions'),
    path('updateposition/', UpdatePositionAPIView.as_view(),name='update-positions'),
    path('positions/', PositionAPIView.as_view(), name='position-list'),
    path('positions/assign/', AssignCarToPositionAPIView.as_view(), name='assign-car-to-position'),
    path('services/', ServiceViewSet.as_view({'get': 'list'}), name='service-list'),
    path('services/<int:pk>/', ServiceViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='service-detail'),
    path('orders/', OrderViewSet.as_view({'get': 'list', 'post': 'create'}), name='order-list-create'),
    path('totalorders/',TotalOrdersAPIView.as_view(),name="totalorder"),
    path('totalshoporders/',ProductOrderListAPIView.as_view(),name="shop-Order"),
    path('discountorders/', ValidateDiscountCodeAPIView.as_view(), name='discount'),
    path('updateorder/', UpdateOrderDetailsAPIView.as_view(), name='update-order-details'),
    path('car/<int:car_id>/', CarDetailView.as_view(), name='car-detail'),
    path('userorders/<int:user_id>/', UserOrdersAPIView.as_view(), name='user-orders'),
    path('usershoporders/<int:user_id>/', UserShopOrdersAPIView.as_view(),name='user-shop-orders'),
    path('totalOrdersPrice/',AllOrdersAPIView.as_view(), name='total-order-price'),
    path('TotalPriceShop/',TotalPriceShopOrdersAPIView.as_view(), name='total-price-shop'),
    path('creatdiscount/',CreateDiscountCodeAPIView.as_view(), name='create-discount'),
    path('positionqeueu/',GetPositionQueueAPIView.as_view(), name='position-queue'),
    path('createproduct/',CreateProductAPIView.as_view(), name='create-product'),
    #??????????????????????????????????????????????????????????????????????????????????
    path('productlist/',ProductListAPIView.as_view(), name='product-list'),
    path('shoporder/',CreateOrderAPIView.as_view(),name='shop-order'),
    path('shoporder/<int:order_id>/update/', UpdatePaymentStatusAPIView.as_view(), name='update_payment_status'),
]
