# Generated by Django 5.0.6 on 2024-06-12 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_alter_position_worker_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='shiftDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
